### ISSUE TITLE
[Hard] Acceptable "booking-level" bureaucracy dependency

### ISSUE THREAD

**Issue by eKristensen** [netgrp/pop-booking#11]
How much is a fair level of bookings? How to build the system in a fair way?

The current house rules does not give a clear indication for a set of rules that can be easily implemented.

The idea is that no one user should be able to take a resource for themselves, but it should still be possible for them to book if nobody else are interested while keeping in mind that a single user can represent more than one resident, e.g. with Canoe bookings.

Hard because of bureaucracy required to create proper policy.

**Comment by eKristensen** [comment]
Maybe just accept the rules as they are?

**Comment by ThomasConrad** [comment]
Dude, I don't understand the rules. There are too many loopholes in the formulation for it to even make sense. At least I think so. How would you formulate something?

I think an essential quality is that you can't hoard items. However we should allow for repeat bookings fx. 24 hours before so that items are not left unused.

**Comment by eKristensen** [comment]
> Det er ikke tilladt at reservere multirummet i mere end 6 timer ad gangen, ved maksimalt 2 reservationer 3 uger frem

There are no loopholes, just rules.

The rule states that in the window that is the next 3 weeks, i.e. 1 814 400 seconds from any given time there can be at most 2 bookings, and each booking can be at most 6 hours long, or 10 800 seconds.

I'd say that a booking counts towards the count for the next three weeks until it has ended.

Actually pretty simple. It does not matter how those bookings are made (other than opening hours restrictions).

**Comment by eKristensen** [comment]
I think I made it hard for ourselves by thinking about what's fair and not. In the end the rules are not that hard to understand.

Whether they are fair or not is another question entirely.

**Comment by ThomasConrad** [comment]
Fair enough, I guess I can implement that. I will have to do a sliding window check of sorts, from a 3 week before and 3 week after the time of the attempted booking to be created. First I can check whether there are already 2 or more bookings in that 6 week window made by the same user/room nr. Then if there are more, then I can check whether 2 of those fall within a 3 week period, which I don't know the best method for, but I mean, it's probably such a quick task that optimum time complexity is completely irrelevant. But just for funsies, do you know of a method to do that in the fewest operations?

**Comment by eKristensen** [comment]
Read the rules :) 

> maksimalt 2 reservationer 3 uger frem

You are not allowed to have a booking beyond the 3 weeks. You only need to check the booking starts in the future and ands before 3 weeks and that there are at most 2 bookings in that period at any time a booking is created.

**Comment by eKristensen** [comment]
No need for at 3+3 week window

I suppose an algorithm could be:

- Get all bookings between now and 3 week forward, including any that start earlier. Bookings that end futher than 3 weeks on should not be possible so that does not matter
- If there are less than 2 bookings then allow booking
- Follow the other booking rules: e.g. max 6 hours, opening hours

Makes sense?

**Comment by ThomasConrad** [comment]
True, true. I had just wanted to keep allowing people to book more than 3 weeks in advance, but we stick to the rules 💪💪💪

**Comment by ThomasConrad** [comment]
gimme 10 mins

**Comment by ThomasConrad** [comment]
Okay, I got stuck trying to make this work in the config files so that the rules could be altered without recompiling the program. Not doing that today, maybe some other day. Now I just hardcoded that items called "meetingroom" will be nerfed.

https://github.com/netgrp/pop-booking/pull/23
