### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by eKristensen** [netgrp/pop-booking#9]
We use Cloudflare, Google reCaptha and our own.

None of them are optional, but I suppose the user would have to accept them somehow.

Idea: Block webpage loading before they are accepted. Set at cookie to save consent.
If user rejects use something like JavaScript. window.close() method

**Comment by ThomasConrad** [comment]
What about this @eKristensen: https://github.com/mCaptcha/mCaptcha.
It's effectively a lot like rate limiting, so I don't know how useful it is, but there would be no GDPR concerns.
I also enabled rate limiting to 5/10s on /api/login endpoint

**Comment by eKristensen** [comment]
I just saw: https://gdpr.eu/cookies/
As long as the cookies come from us and are strictly necessary we do not need to ask for consent, only explain why they are needed.

mCaptcha looks interesting, maybe we should try it. Not using Cloudflare and Google would be really nice. Could it maybe also be used for print.pop.dk aka https://github.com/netgrp/pop-print ?

**Comment by eKristensen** [comment]
Also the only self-hosted solution listed here: https://european-alternatives.eu/category/captcha-services - If that is worth anything...

**Comment by ThomasConrad** [comment]
Timeout has been implemented, no need for cookies or consent.
